"""
app/models/recruiter.py — WHY IT EXISTS
=========================================
Defines the Recruiter data structure. One class does two jobs:
  1. SQLModel with table=True  → creates the 'recruiter' table in SQLite
  2. Inherits from SQLModel     → validates API input/output like Pydantic

Status flow:
  pending → email_found → email_failed → ready → sent / failed

This lets you filter recruiters by what step they're on.
"""

from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


class RecruiterStatus(str, Enum):
    """
    str + Enum = values are strings ("pending"), not integers.
    FastAPI serializes these as readable strings in JSON.
    """
    pending      = "pending"       # Just added, no email yet
    email_found  = "email_found"   # Hunter.io found an email
    email_failed = "email_failed"  # Hunter.io couldn't find email
    ready        = "ready"         # Email generated by Claude, ready to send
    sent         = "sent"          # Email delivered via Gmail
    failed       = "failed"        # Send attempt failed


class RecruiterBase(SQLModel):
    """
    Shared fields between the DB model and API schemas.
    Not a table itself — just a base to avoid repeating fields.
    """
    first_name:   str            = Field(description="Recruiter's first name")
    last_name:    str            = Field(description="Recruiter's last name")
    company:      str            = Field(description="Company they work at")
    company_domain: Optional[str] = Field(default=None, description="e.g. google.com — auto-inferred if blank")
    title:        Optional[str]  = Field(default=None, description="Job title (optional, used by Claude for personalization)")
    linkedin_url: Optional[str]  = Field(default=None, description="Their LinkedIn (optional)")


class Recruiter(RecruiterBase, table=True):
    """
    THE DATABASE TABLE.
    table=True tells SQLModel to create a real SQL table for this class.
    
    Fields added here (beyond RecruiterBase) are tracking/system fields
    the user doesn't supply — they're set by the app.
    """
    id:           Optional[int]  = Field(default=None, primary_key=True)
    # primary_key=True → auto-incrementing integer ID
    
    email:        Optional[str]  = Field(default=None)
    # Filled in by Hunter.io service
    
    email_pattern: Optional[str] = Field(default=None)
    # Which pattern Hunter.io used: "firstname.lastname" or "f.lastname"
    
    hunter_confidence: Optional[int] = Field(default=None)
    # Hunter.io confidence score 0-100. Higher = more reliable.
    
    status:       RecruiterStatus = Field(default=RecruiterStatus.pending)
    # Current pipeline stage
    
    generated_subject: Optional[str] = Field(default=None)
    generated_body:    Optional[str] = Field(default=None)
    # Claude's generated email, stored before sending
    
    error_message: Optional[str] = Field(default=None)
    # If something failed, store why here
    
    created_at:   datetime = Field(default_factory=datetime.utcnow)
    updated_at:   datetime = Field(default_factory=datetime.utcnow)


class RecruiterCreate(RecruiterBase):
    """
    What the API accepts when creating a recruiter.
    Inherits all RecruiterBase fields. No ID (that's assigned by DB).
    """
    pass


class RecruiterRead(RecruiterBase):
    """
    What the API returns when reading a recruiter.
    Includes the DB-assigned fields the user didn't supply.
    """
    id:               int
    email:            Optional[str]
    hunter_confidence: Optional[int]
    status:           RecruiterStatus
    generated_subject: Optional[str]
    generated_body:    Optional[str]
    error_message:    Optional[str]
    created_at:       datetime
    updated_at:       datetime

    class Config:
        from_attributes = True  # Allows creating from SQLModel ORM object
